### ISSUE TITLE
Odd results when setting volume indices

### ISSUE THREAD

**Issue by vincenzoml** [niivue/niivue#243]
In the following code fragment: 

1) if I do not use "setVolume", no matter in which order the two "addVolume" are done, I only see the binary "seg" image.

2) if I uncomment "setVolume" then I get something similar to ordering layers, but oddly, the "seg" image has a semi-transparent background (just like in the screenshot I attached in my other comment)

Let me know how to provide more information, or maybe this is not a bug at all?

        let url1 = "/api/getLayer/BraTS_2019_HGG_Augmented/BraTS19_2013_10_1/BraTS19_2013_10_1_seg.nii.gz"
        let url2 = "/api/getLayer/BraTS_2019_HGG_Augmented/BraTS19_2013_10_1/BraTS19_2013_10_1_flair.nii.gz"
        let img1 = await NVImage.loadFromUrl(url1)
        let img2 = await NVImage.loadFromUrl(url2)
        nv.addVolume(img1)
        nv.addVolume(img2)
        // nv.setVolume(img1,0)
        // nv.setVolume(img2,1)

**Comment by vincenzoml** [comment]
Additionally, in my main program, I have the following volume order (printed by attaching the url to each "img" and then inspecting the "nv.volumes" array directly):

`['/api/getLayer/BraTS_2019_HGG_Augmented/BraTS19_2013_10_1/BraTS19_2013_10_1_seg.nii.gz', '/api/getLayer/BraTS_2019_HGG_Augmented/BraTS19_2013_10_1/BraTS19_2013_10_1_flair.nii.gz']`

but I still see the "flair" image below the seg as per the attached screenshot

![image](https://user-images.githubusercontent.com/2283125/154819619-91a2582e-93c7-4057-85fc-f319cfe36ede.png)

**Comment by hanayik** [comment]
Thanks for reporting the addVolume issue. It likely needs to be updated due to other changes recently. It wasn't caught in testing because there is no test for addVolume yet. I'll be sure to add a new test as well. 

BTW, @vincenzoml I would strongly recommend updating NiiVue to 0.20.0

We just released it and it fixed a bug related to displaying images saved in various spatial orientations. 

The addVolume fix will be released in 0.20.1 probably. 

All NiiVue versions less than 1.0.0 are considered beta versions. We are working towards a 1.0.0 release and your bug hunting and comments have been very helpful. Thanks!

**Comment by vincenzoml** [comment]
Hi, I am using niivue in a new project which is going to be released as open source as soon as it's finished. Niivue is a great viewer and I think we could also consider e.g. a joint application for funding at some point. Said this, I've updated to 0.20.0 but I still have an issue with orientation: I have a file where the s-matrix is wrong but the q-matrix is correct. Is it possible to disable the s-matrix entirely in niivue?

**Comment by hanayik** [comment]
@vincenzoml, at the moment Niivue uses the form matrix and ignores the qform. If you email a problematic image (suggested by @neurolabusc) then we can investigate more. 

You might also want to try a temporary fix for problematic images to see if they will work in Niivue:

`fslorient -copyqform2sform my_image.nii.gz`

**Comment by vincenzoml** [comment]
Hi,  great suggestion to use fslorient. In my use case, it's a bug of an old version of ITK which is fixed in recent versions, so I will solve the problem by upgrading the library used in voxlogica. However, I think in general it may be useful to have an option to ignore / use either qform or sform. I've been suggested by the medical physicist in our team that very often only the q-form is used so maybe it would be good to also use it. Would you like me to submit a wishlist item on that?

**Comment by hanayik** [comment]
@vincenzoml, great! glad fslorient worked. 

Yes, can you start a new issue for this. 

some thoughts below...

Agreed, we have just recently started to discuss adding a new option to allow users to prefer the sform or qform when loading a new `NVImage` from a URL or File. 

As you have experienced, the preference of sform or qform is indeed software specific, and in some cases there is still variability in how software packages treat the sform and qform fields when writing data (for example, the bug in ITK). 

FSL_view is now deprecated (has been for some time), and if you're using FSL then FSLeyes is the preferred viewer (for full disclosure, I'm on the FSL software dev team, but don't contribute much to the FSLeyes code). I _think_ FSLeyes will prefer the sform since it uses nibabel (https://open.win.ox.ac.uk/pages/fsl/fsleyes/fsleyes/userdoc/display_space.html#world-coordinate-system). 

I'm not sure of the preference of MRIcroGL since I'm not familiar with the code base. NiiVue is trying to combine useful features from different viewers, but does inherit most of its volume rendering functionality from MRIcroGL (https://github.com/rordenlab/MRIcroGL). 

I'm thinking that perhaps we should adopt the logic that nibabel use and then document that well in NiiVue. I think @neurolabusc should weigh in here though.

**Comment by neurolabusc** [comment]
We need to update NiiVue to handle NIfTI images as they are seen in the wild. 

However, any tool which creates a NIfTI 9 DoF QForm should always create a 12 DoF SForm (since it can be done losslessly). The rationale for the two orientations is that the more constrained QForm is good enough to store a NIFTI_XFORM_SCANNER_ANAT  (though not gantry tilt) while the SForm can store a full affine NIFTI_XFORM_ALIGNED_ANAT. It is unfortunate that ITK/VTK gave precedence to the QForm over the SForm and often mangled the SForm. This has caused issues for interoperability with other tools. I did warn the ITK developers about the consequences of these choices over a decade ago. I do think ITK has some outstanding functions, and is a terrific resource. However, people who use this toolkit need to be wary that it makes different assumptions than other tools in our field.

**Comment by afni-dglen** [comment]
@vincenzoml, I have noticed the left-right flipping problem with ITK-snap recently. Modifying an existing NIFTI dataset resulted in a consistent flip. This was part of a right-hemisphere macaque brain atlas, so the error was obvious. We reset the orientation with "3dresample -orient" to the correct orientation for the dataset. While this problem was obvious for this particular dataset, it likely won't be for most others. We published a paper on general findings of this sort in FMRI databases. [https://www.frontiersin.org/articles/10.3389/fninf.2020.00018/full](https://www.frontiersin.org/articles/10.3389/fninf.2020.00018/full)

**Comment by afni-dglen** [comment]
Also in AFNI's .afnirc resource file, one can set the qform/sform priority with this variable (described in README.environment):
--------------------------------
Variable: AFNI_NIFTI_PRIORITY
--------------------------------
Sets preference for NIFTI files to use sform or qform codes and
matrices to determine space, origin and orientation. Set to 'S' or 'Q'
for sform or qform respectively. If not set, NIFTI files are read
using the non-zero form code or the sform code if both are set.

**Comment by hanayik** [comment]
@vincenzoml , the addVolume errors should now be fixed in the latest version (0.21.1)

**Comment by vincenzoml** [comment]
Thanks a lot, I'm a bit left behind but will test this as soon as possible.

**Comment by vincenzoml** [comment]
@hanayik  the bug is fixed, indeed, thank you very much.
